### ISSUE TITLE
Wrong serialization with ByteArray type

### ISSUE THREAD

**Issue by mepsoid** [soywiz/haxe-ws#13]
When library works as flash target inside browser it uses internal js websockets at class `WebSocketFlashExternalInterface`. Both functions `sendBytes(message:Bytes)` and `sendString(message:String)` have same implementation. But when I'm sending some `ByteArray` (=`haxe.io.Bytes` at flash target) data it's serialized like [object Object] and sending as text frame instead of binary one.
Anyway implementation for local flash run `WebSocketGeneric` works fine.
I suppose that this js wrapper was made to evade security issues with requesting policy by flash player. But this implementation doesn't work as expected at all.

**Comment by soywiz** [comment]
I'm not maintaining this project anymore by myself. But you can make a PR with a fix, and I will publish it.

For what you said I think that that Bytes should be transformed into BytesData before calling the _send method.
http://api.haxe.org/haxe/io/Bytes.html#getData
https://github.com/soywiz/haxe-ws/blob/master/src/haxe/net/impl/WebSocketFlashExternalInterface.hx#L77
Can you try to add `message.getData` here. If it works, please do a pull request and I will merge it.

**Comment by mepsoid** [comment]
Formally you are right, it's typo at class `WebSocketFlashExternalInterface`. But substitution of `message.getData()` isn't enough to solve the problem, because in this case we're passing actionscript `ByteArray` instance to javascript function through `ExternalInterface`. It isn't possible by this way, all the data became as dumb js `Object` instance with some fields set.
It can be solved by serialization-deserialization to `String` type but this solution looks quite dirty for me.

**Comment by soywiz** [comment]
As far as I have seen, people suggest just that. They suggest base64. But we can use hex too. ExternalInterface is a bit dirty already. As far as I know they internally use xml. Anyway it is usually fast. So as long as it works. It's fine.

The point using javascript is to improve connection times. Usually flash has a several second delay between asking for the xml permissions and actually connecting. We ended doing this for that reason. But in our case we didn't need the binary stuff. So I missed that.

**Comment by mepsoid** [comment]
I've done this one with `Array` serialization.

**Comment by soywiz** [comment]
Just uploaded 1.0.1 with your change. Thanks for the PR!
