### ISSUE TITLE
A server must not mask any frames that it sends to the client.

### ISSUE THREAD

**Issue by ovidiugabriel** [soywiz/haxe-ws#37]
Hello,

I have the following error using haxe-ws (only on Chrome and Opera). It seem to work fine on Firefox.

```
WebSocket connection to 'ws://localhost:8582/' failed: 
A server must not mask any frames that it sends to the client.
```

What I am doing wrong?

**Comment by pixelsyntax** [comment]
This problem is already fixed in github, but the change has not been propagated to the version on haxelib. You will need to either clone haxe-ws from github directly or modify the haxelib version as per https://github.com/soywiz/haxe-ws/pull/27

**Comment by ovidiugabriel** [comment]
This is true. I already patched this in my project. It is unfortunate that haxelib does not have this fix yet. Any plans to publish new versions to haxelib?

**Comment by endel** [comment]
I've forked this project and will keep it updated here https://github.com/colyseus/haxe-ws

Made some changes on it to fix deprecation warnings on haxe4, and fixed the `sec-websocket-key` for handshake.
